spring:
  profiles: dev
  jackson:
    serialization:
      write-dates-as-timestamps: "false"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      path: /h2-console
      settings:
        trace: "false"
        web-allow-others: "false"
      enabled: "true"
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    org:
      springframework: debug
